[build]
base = "Angular/01 - Fundamentos/gerador-certificado"
command = "ng build --configuration=production"
publish = "dist/gerador-certificado"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
